pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@3
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    ScriptType: 'InlineScript'
    Inline: 'Remove-AzureSBNamespace -Name BookieBreakerTEST -Force'
    azurePowerShellVersion: 'LatestVersion'