pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@3
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    ScriptType: 'InlineScript'
    Inline: 'Remove-AzureRmServiceBusNamespace -ResourceGroup testresource -NamespaceName BookieBreakerTEST'
    azurePowerShellVersion: 'LatestVersion'