pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@4 # Teardown Service Bus
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    ScriptType: 'InlineScript'
    Inline: 'Remove-AzureRmServiceBusNamespace -ResourceGroup tesresource -NamespaceName BookieBreakerBusTEST'
    azurePowerShellVersion: 'LatestVersion'