pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@3 # Teardown SQL Server
  name: "Teardown_SQL_Server"
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    ScriptPath: 'Andgasm.BB.Infrastructure/Andgasm.BB.SQLServer.Deploy/Teardown-AzureResourceGroup.ps1'
    ScriptArguments: -ResourceGroupName 'BookieBreaker' -ResourceGroupLocation 'westeurope'
    azurePowerShellVersion: LatestVersion
- task: AzurePowerShell@3 # Create SQL Server
  name: "Create_SQL_Server"
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    ScriptPath: 'Andgasm.BB.Infrastructure/Andgasm.BB.SQLServer.Deploy/Deploy-AzureResourceGroup.ps1'
    ScriptArguments: -ResourceGroupName 'BookieBreaker' -ResourceGroupLocation 'westeurope'
    azurePowerShellVersion: LatestVersion
- task: AzurePowerShell@3 # Teardown Service Bus
  name: "Teardown_Service_Bus"
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    ScriptPath: 'Andgasm.BB.Infrastructure/Andgasm.BB.ServiceBus.Deploy/Teardown-AzureResourceGroup.ps1'
    ScriptArguments: -ResourceGroupName 'BookieBreaker' -ResourceGroupLocation 'westeurope'
    azurePowerShellVersion: LatestVersion
- task: AzurePowerShell@3 # Create Service Bus
  name: "Create_Service_Bus"
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    ScriptPath: 'Andgasm.BB.Infrastructure/Andgasm.BB.ServiceBus.Deploy/Deploy-AzureResourceGroup.ps1'
    ScriptArguments: -ResourceGroupName 'BookieBreaker' -ResourceGroupLocation 'westeurope'
    azurePowerShellVersion: LatestVersion
- task: AzurePowerShell@4 # Teardown Season Participants API App Service
  name: "Teardown_Season_Participants_API_App_Service"
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    ScriptPath: 'Andgasm.BB.Infrastructure/Andgasm.BB.SeasonParticipant.Deploy/Teardown-AzureResourceGroup.ps1'
    ScriptArguments: -ResourceGroupName 'BookieBreaker' -ResourceGroupLocation 'westeurope'
    azurePowerShellVersion: LatestVersion
- task: AzurePowerShell@3 # Create Season Participants API App Service
  name: "Create_Season_Participants_API_App_Service"
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    ScriptPath: 'Andgasm.BB.Infrastructure/Andgasm.BB.SeasonParticipant.Deploy/Deploy-AzureResourceGroup.ps1'
    ScriptArguments: -ResourceGroupName 'BookieBreaker' -ResourceGroupLocation 'westeurope'
    azurePowerShellVersion: LatestVersion