pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@3 # Create SQL Server
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    ScriptPath: 'Andgasm.BB.Infrastructure/Andgasm.BB.SQLServer.Deploy/Deploy-AzureResourceGroup.ps1'
    ScriptArguments: -ResourceGroupName 'BookieBreaker' -ResourceGroupLocation 'westeurope'
    azurePowerShellVersion: LatestVersion