pool:
  name: Hosted Windows 2019 with VS2019
  demands: azureps

steps:
- task: AzurePowerShell@3
  inputs:
    azureSubscription: 'AzureRmPipeline-conn'
    ScriptPath: 'Andgasm.BookieBreaker.Infrastructure/Deploy-AzureResourceGroup.ps1'
    ScriptArguments: -ResourceGroupName 'testresource' -ResourceGroupLocation 'centralus'
    azurePowerShellVersion: LatestVersion